version: "3"
services:
  mysql-learners:
    image: mysql:5.7.25
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=learners
    ports:
      - "3306:3306"
  learners-container:
    image: learners-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-learners:3306/learners?serverTimezone=UTC&autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    build:
      context: "./"
      dockerfile: Dockerfile
    depends_on:
      - mysql-learners